<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ccat.common.utils" Version="1.0.1" />
        <PackageReference Include="MSTest" Version="4.0.2"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting"/>
    </ItemGroup>

    <ItemGroup>
      <None Remove="TestData\DefaultLevelCurve.json" />
      <Content Include="TestData\DefaultLevelCurve.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="TestData\DefaultCostCurve.json" />
      <Content Include="TestData\DefaultCostCurve.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\LevelManager\LevelManager.csproj" />
    </ItemGroup>

</Project>
