<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <None Include="..\README.md"
              Pack="true"
              PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ccat.common.utils" Version="1.0.1" />
    </ItemGroup>
    
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        
        <PackageId>CCAT.Gacha.LevelManager</PackageId>
        
        <Authors>MM</Authors>
        <PackageDescription>Leveling System</PackageDescription>
        <Description>Leveling System.</Description>
        <RepositoryUrl>https://github.com/markm001/level-manager</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        
        <Title>CCAT.Common.LevelManager</Title>
    </PropertyGroup>
</Project>
